# Generated by Django 4.1.3 on 2023-01-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Orden', 'verbose_name_plural': 'Ordenes'},
        ),
    ]
